do $$
declare res text := ''; n int; uid uuid := gen_random_uuid(); pid bigint; ex bigint; ac bigint;
begin
  insert into auth.users (id, email, instance_id, aud, role) values (uid, 'r@itmk.test', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated');
  insert into public.usuario (id, nome, email) values (uid, 'R', 'r@itmk.test');
  insert into public.pagador (cpf) values ('99988877766') returning id into pid;
  begin set local role anon; perform 1 from public.pagador limit 1; res := res || 'ANON_LEU(ERRO); '; exception when insufficient_privilege then res := res || 'anon_negado; '; end;
  reset role;
  begin set local role authenticated; perform 1 from public.cobranca limit 1; res := res || 'AUTH_LEU(ERRO); '; exception when insufficient_privilege then res := res || 'authenticated_negado; '; end;
  reset role;
  set local role itmk_app;
  select count(*) into n from public.pagador; res := res || 'app_sem_contexto_ve=' || n || '; ';
  begin insert into public.pagador (cpf) values ('11100011100'); res := res || 'APP_INSERIU_SEM_CONTEXTO(ERRO); '; exception when others then res := res || 'app_sem_contexto_nao_grava; '; end;
  perform set_config('itmk.ator_tipo', 'usuario', true); perform set_config('itmk.usuario_id', uid::text, true);
  insert into public.pagador (cpf) values ('11100011100');
  res := res || 'app_grava_pagador; ';
  begin delete from public.pagador where cpf = '11100011100'; res := res || 'APP_APAGOU(ERRO); '; exception when insufficient_privilege then res := res || 'app_nao_apaga; '; end;
  begin update public.auditoria set motivo = 'x' where id = 1; res := res || 'APP_EDITOU_AUDITORIA(ERRO); '; exception when insufficient_privilege then res := res || 'app_nao_edita_auditoria; '; end;
  begin truncate public.auditoria; res := res || 'APP_TRUNCOU(ERRO); '; exception when insufficient_privilege then res := res || 'app_nao_trunca; '; end;
  begin select count(*) into n from vault.secrets; res := res || 'APP_LEU_VAULT(ERRO); '; exception when insufficient_privilege then res := res || 'app_nao_le_vault; '; end;
  reset role;
  set local role itmk_robo;
  perform set_config('itmk.ator_tipo', 'robo', true);
  begin perform 1 from public.auditoria limit 1; res := res || 'ROBO_LEU_AUDITORIA(ERRO); '; exception when insufficient_privilege then res := res || 'robo_nao_le_auditoria; '; end;
  begin insert into public.pagador (cpf) values ('22200022200'); res := res || 'ROBO_CRIOU_PAGADOR(ERRO); '; exception when insufficient_privilege then res := res || 'robo_nao_cria_pagador; '; end;
  ex := public.robo_registrar_execucao(now() - interval '1 minute', now(), '1.0', 1, 'concluída');
  ac := public.robo_registrar_acao(ex, null, pid, 'lembrete', 'r1', 'whatsapp', 'chave-x', 'ignorado', 'fora do horario', false);
  res := res || 'robo_registra=' || (ac is not null) || '; ';
  begin perform 1 from public.robo_execucao limit 1; res := res || 'ROBO_LEU_EXECUCAO(ERRO); '; exception when insufficient_privilege then res := res || 'robo_so_insere_execucao; '; end;
  begin update public.robo_acao set motivo = 'x' where id = ac; res := res || 'ROBO_EDITOU_ACAO(ERRO); '; exception when insufficient_privilege then res := res || 'robo_nao_edita_acao; '; end;
  reset role;
  set local role itmk_relatorio;
  begin perform 1 from public.cobranca limit 1; res := res || 'RELATORIO_LEU_TABELA(ERRO); '; exception when insufficient_privilege then res := res || 'relatorio_nao_le_tabela; '; end;
  select count(*) into n from public.v_dashboard_indicadores; res := res || 'relatorio_le_visao=' || n || '; ';
  begin insert into public.pagador (cpf) values ('33300033300'); res := res || 'RELATORIO_ESCREVEU(ERRO); '; exception when insufficient_privilege then res := res || 'relatorio_nao_escreve; '; end;
  begin perform public.itmk_conferir_cadeias(); res := res || 'RELATORIO_CHAMOU_FUNCAO_INTERNA(ERRO); '; exception when insufficient_privilege then res := res || 'funcao_interna_fechada; '; end;
  reset role;
  raise exception 'TESTE_OK_ROLLBACK %', res;
end $$;
